name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: sh ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        path: linux/arch/i386/boot/bzImage
    - uses: actions/upload-artifact@v2
      with:
        path: linux/.config
